### ISSUE TITLE
No transformation found from EPSG:31256 to EPSG:4326

### ISSUE THREAD

**Issue by ebocher** [orbisgis/cts#145]
This issue has been  reported on H2 database group.
See : https://groups.google.com/g/h2-database/c/kR10UNaGs00

CTS unit for EPSGTransformTest
```
  @Test
    void testFrenchEPSGCodeFrom31256To4326() throws Exception {
        String csNameSrc = "EPSG:31256"; //Input EPSG
        double[] pointSource = new double[]{-38048.66 , 389405.66};
        String csNameDest = "EPSG:4326";  //Target EPSG
        double[] pointDest = new double[]{15.815805676616735 ,48.64153355841612};
        double tolerance = 10E-9;
        CoordinateReferenceSystem inputCRS = cRSFactory.getCRS(csNameSrc);
        CoordinateReferenceSystem outputCRS = cRSFactory.getCRS(csNameDest);
        verbose = false;
        double[] result = transform((GeodeticCRS) inputCRS, (GeodeticCRS) outputCRS, pointSource);
        assertTrue(checkEquals2D("EPSG:31256 to EPSG:4326 ", result, pointDest, tolerance));
    }
```

**Comment by ebocher** [comment]
Another issue is reported in H2GIS when a transform is created from 2249 to 4326

https://github.com/orbisgis/h2gis/issues/1266

@mukoki 
Can you take a look inside CTS ?
You will be much more efficient than me

**Comment by youseeus** [comment]
the same for "from EPSG:4326 to EPSG:31467"
is there any update? i would like to use this Lib but 31256

**Comment by bacek** [comment]
Same for 26911 and 3857 web merkator.

**Comment by tilovillwock** [comment]
I ran into the same problem trying to transform coordinates from `31466` to `25832`. I studied the code and as far as I can tell this error occurrs when either the source or target [EPSG definition](https://github.com/orbisgis/cts/blob/master/src/main/resources/org/cts/registry/epsg#L10063) have no valid `towgs84` parameter. See:

* https://github.com/orbisgis/cts/blob/master/src/main/java/org/cts/datum/GeodeticDatum.java#L597
* https://github.com/orbisgis/cts/blob/master/src/main/java/org/cts/datum/GeodeticDatum.java#L598
* https://github.com/orbisgis/cts/blob/master/src/main/java/org/cts/op/CoordinateOperationFactory.java#L220

So maybe adding an updated epsg defintion file to `src/main/resources/org/cts/registry` fixes the problem. I haven't tested this yet though.

**Comment by ebocher** [comment]
Thanks a lot for feedbak.
Currently we have no time and no ressources to fix this issue, so any PR are welcome !
Sorry for that.

**Comment by MarkusProgramer** [comment]
I finally found the problem.
You have to edit the code like I mentioned before in the GeodeticDatum.java file. I only forgot to delete some test code.

`public final static GeodeticDatum HERMANNSKOGEL = new GeodeticDatum( new Identifier("EPSG", "4312", "Militar-Geographische Institut", "MGI"), PrimeMeridian.GREENWICH, Ellipsoid.BESSEL1841, SevenParameterTransformation.createBursaWolfTransformation(577.326,90.129,463.919,5.1366,1.4742,5.2970,2.4232), new GeographicExtent("Austria", 46.4, 49.02, 9.53, 17.17), "", "");`

Instead of null you have to call the method `SevenParameterTransformation.createBursaWolfTransformation()`. The parameters for the specific transformations can be found in the internet. This should be done for all frames of reference.

**Comment by ebocher** [comment]
Fix done in CTS see  https://github.com/orbisgis/cts/pull/147
Note that NAD83 is not yet supported yet.

**Comment by ebocher** [comment]
See https://github.com/orbisgis/cts/issues/127
